[package]
name = "polylux"
version = "0.3.1"
entrypoint = "polylux.typ"
authors = ["Andreas Kr√∂pelin", "contributors"]
license = "MIT"
description = "Presentation slides creation with Typst"
repository = "https://github.com/andreasKroepelin/polylux"
exclude = ["README.md"]
